### ISSUE TITLE
Missing toolbar icons, when used with "Sourcedialog" plugin

### ISSUE THREAD

**Issue by aik099** [w8tcha/CKEditor-CodeMirror-Plugin#142]
The #58 issue is back. The CKEditor build script builds `icons.png` file from `icons` folder of each addon and then deletes addon `icons` folder (because they're in the sprite). The CodeMirror CSS however isn't using generated CSS of CKEditor to display toolbar buttons, but is using own CSS that still refers to deleted icons.

CSS fragment in `ckeditor/skins/moono/editor.css` file (skin of CKEditor):

```css
...
.cke_button__autoformat_icon {background: url(icons.png?t=230f715) no-repeat 0 -2088px !important;}
.cke_button__commentselectedrange_icon {background: url(icons.png?t=230f715) no-repeat 0 -2112px !important;}
.cke_button__searchcode_icon {background: url(icons.png?t=230f715) no-repeat 0 -2136px !important;}
.cke_button__uncommentselectedrange_icon {background: url(icons.png?t=230f715) no-repeat 0 -2160px !important;}
...
```

CSS fragment in `ckeditor/plugins/codemirror/css/codemirror.min.css` file:

```css
.searchCodeButton span,.autoFormat span,.CommentSelectedRange span,.UncommentSelectedRange span{width:16px;height:16px;margin-left:6px}
.searchCodeButton span{background:url("../icons/searchcode.png") no-repeat}
.autoFormat span{background:url("../icons/autoformat.png") no-repeat}
.CommentSelectedRange span{background:url("../icons/commentselectedrange.png") no-repeat}
.UncommentSelectedRange span{background:url("../icons/uncommentselectedrange.png") no-repeat}
```

![00001496](https://user-images.githubusercontent.com/1277526/38367527-9b0cd060-38eb-11e8-9436-4b8eed7ca9e0.png)

Related: https://dev.ckeditor.com/ticket/11776

I see several solutions:

1. change CSS/HTML of toolbar buttons to use CKEditor generated CSS
2. rename `icons` folder of the plugin to something else, so that they won't be deleted by CKEditor build script
